// Hand-written question-and-answer pairs for each Knowledge Centre article.
// Rendered as a visible "Frequently asked questions" section on the article and
// emitted as FAQPage JSON-LD (the visible text must match the schema text).
// Every answer is drawn from the article it belongs to — keep them in sync when
// an article's figures change.
export type FaqEntry = [question: string, answer: string];

export const postFaqs: Record<string, FaqEntry[]> = {
  'timber-seasoning-sri-lanka-complete-guide': [
    ['Why can\'t air seasoning reach 12–15% moisture content in Sri Lanka?', 'Because of ambient humidity. In coastal and lowland Sri Lankan conditions, air-dried timber plateaus at around 18–22% moisture content because the humid air will not accept more moisture from the wood. Air seasoning is also slow for thick sections and gives no protection against insect attack while the timber dries.'],
    ['How long does kiln seasoning take?', 'In an automated kiln most loads reach a verified 12–15% moisture content in 3–12 days, depending on species and thickness, regardless of the weather. Air seasoning first under cover to about 25–30% moisture content and then finishing in the kiln minimises kiln time and cost.'],
    ['How do I choose a timber seasoning provider in Sri Lanka?', 'Ask three questions: what final moisture content is targeted and how it is verified (calibrated meters, recorded per batch); whether the kiln schedule is matched to the species; and what happens after seasoning, since dried timber left in a humid yard reabsorbs moisture and should be stored under cover and treated or dispatched promptly.'],
  ],
  'ispm-15-certification-sri-lanka-exporters-guide': [
    ['Who can apply the IPPC mark in Sri Lanka?', 'Only facilities registered with the National Plant Quarantine Service (NPQS) of Sri Lanka, and only on wood that facility actually treated. You cannot heat-treat packaging yourself or buy an IPPC stamp. The mark carries the IPPC symbol, the country code LK, a unique facility registration number and the treatment code HT.'],
    ['What temperature and time does ISPM 15 heat treatment require?', 'The core of the wood must reach at least 56°C and be held there for a minimum of 30 minutes, verified by probes in the thickest pieces. Heat treatment (HT) is the standard method in Sri Lanka; methyl bromide fumigation is being phased out in most markets.'],
    ['What happens if wooden packaging is not ISPM 15 compliant?', 'Typical outcomes are that the shipment is held at port while the packaging is treated or destroyed at the importer\'s expense, the packaging is rejected and the goods must be re-packed, or in the strictest markets the whole consignment is refused entry and returned. Australia and New Zealand are known for particularly rigorous enforcement.'],
    ['Is kiln-dried wood automatically ISPM 15 compliant?', 'No. Kiln drying targets moisture content and takes days, while ISPM 15 heat treatment targets core temperature and takes hours. The treatment must be run and documented specifically against the standard by a registered facility.'],
  ],
  'kiln-drying-cost-sri-lanka-what-determines-price': [
    ['How much does kiln drying cost per cubic foot in Sri Lanka?', 'There is no honest single price per cubic foot. Kiln drying is priced on chamber time, which varies with species, thickness, starting moisture and load volume, so reputable facilities quote per batch once they know your species, dimensions, quantity and starting condition.'],
    ['What factors determine the price of kiln drying?', 'Four factors: species (dense hardwoods like teak and kumbuk can take two to three times as long as rubberwood or pine), thickness (drying time rises roughly with the square of thickness), initial moisture content (green timber at 60–80% takes far longer than air-dried timber at 25–30%), and volume and stacking (full, single-species loads are most economical).'],
    ['How can I reduce my kiln drying cost?', 'Air-dry timber under cover first to about 25–30% moisture content, saw to final thickness before drying, send full loads of one species at one thickness, and book chamber time in advance rather than paying for urgency.'],
  ],
  'timber-decking-outdoor-use-sri-lanka': [
    ['Which timber is best for outdoor decking in Sri Lanka?', 'Teak is the traditional premium choice because its natural oils give genuine decay resistance, and kumbuk and other dense local hardwoods also perform well when properly treated. Rubberwood should never be used outdoors. Even durable species have perishable sapwood, so treatment still matters.'],
    ['Why is VPI treatment needed for outdoor timber?', 'Surface-applied preservatives protect only a few millimetres, and every cut, drill hole or check exposes bare wood where decay and termites begin. Vacuum pressure impregnation drives preservative through the cross-section, so VPI-treated timber exposed by cutting is still protected.'],
    ['How long does a timber deck last in Sri Lanka?', 'A VPI-treated, correctly detailed hardwood deck is realistically a 15-year-plus structure with basic maintenance. The same timber, surface-treated and carelessly detailed, can need major repairs within three to five years.'],
  ],
  'common-furniture-defects-incorrect-timber-drying': [
    ['What causes furniture panels to warp after delivery?', 'A moisture content mismatch. A panel assembled at higher moisture content than the customer\'s environment dries unevenly, because one face may be sealed or covered, and cups toward the drier face. Processing panels at 12–15% moisture content, the equilibrium range for Sri Lankan interiors, prevents it; a panel processed at 20% can lose 5–8% of its width in service.'],
    ['Why do furniture joints open and finishes crack?', 'Tenons and dowels shrink across the grain as over-wet timber dries in service, opening gaps proportional to how far moisture content was above the service level. Finishes crack for the same reason: the film is bonded to the surface and goes into tension as the wood shrinks.'],
    ['Why do beetle holes appear in new rubberwood furniture?', 'This is powder post beetle infestation. It happens when timber was not kiln-dried, was kiln-dried but stored long enough to be re-infested, or was inadequately treated. Kiln drying kills existing beetle stages and VPI treatment, done in the correct sequence, prevents re-infestation.'],
  ],
  'export-furniture-timber-requirements': [
    ['What moisture content do export furniture buyers require?', 'The most common specification is 8–12% moisture content for furniture destined for air-conditioned retail and residential environments in Europe and the Gulf states. That is lower than the 12–15% typical of Sri Lankan kiln drying, so an extended cycle or a final conditioning stage may be needed.'],
    ['What treatment documents do export furniture buyers ask for?', 'Most European and Australian buyers want a treatment certificate confirming the species, treatment method (kiln drying plus VPI, or kiln drying alone), treatment date and chemical used. Some also require the treating facility to be third-party certified to an international standard.'],
    ['Does export furniture need ISPM 15 treatment?', 'The furniture timber itself needs treatment against beetles, but wooden crates, pallets and dunnage used for shipping must separately be ISPM 15 heat-treated to a 56°C core temperature for 30 continuous minutes by an IPPC-registered facility and marked with the IPPC mark. Both are required for export.'],
  ],
  'furniture-timber-sourcing-sri-lanka': [
    ['What should a furniture timber sourcing specification include?', 'Four things: species and grade, moisture content (target and tolerance, with measurement records), treatment (kiln drying and VPI for rubberwood, with batch records) and dimensions (nominal and acceptable actual sizes, allowing for drying shrinkage).'],
    ['What is a normal degrade rate for kiln-dried rubberwood?', 'Rubberwood from a well-managed kiln with a correct schedule typically produces 8–15% degrade for furniture production. Poorly managed air-drying or an aggressive kiln schedule can produce 25–40%, which eliminates any price advantage.'],
    ['How should I compare timber suppliers beyond price?', 'Compare the cost per square metre of usable, defect-free, dried and treated component, not the price per cubic metre of raw timber. Also check minimum lead time, batch size, ability to commit to a regular supply schedule, the dispute process, and whether the supplier can state its degrade rate by species and thickness.'],
  ],
  'gluing-jointing-kiln-dried-timber': [
    ['What moisture content is best for gluing timber?', 'For PVA and UF adhesives the optimal range is 10–15% moisture content. At 6–8% the wood is too dry and starves the glue line, at 18–22% it dilutes the adhesive and slows curing, and above 22% a joint may look sound until the timber dries and moves in service.'],
    ['Why do glue joints fail on teak?', 'Teak\'s natural surface oils. Wipe both mating faces with an acetone or toluene-based solvent and let it evaporate completely before applying adhesive; gluing to an un-wiped teak surface produces adhesive failure consistently.'],
    ['How fresh should a timber surface be before gluing?', 'Freshly machined, within 24 hours and ideally within a few hours. Older surfaces develop an oxidised, case-hardened layer that resists adhesive and should be lightly re-planed, and dust should be blown or wiped off immediately before applying adhesive.'],
  ],
  'finishing-kiln-dried-timber-moisture-effect': [
    ['What moisture content should timber be before finishing?', 'The equilibrium moisture content of where the piece will be used: 12–14% for air-conditioned interiors in Sri Lanka, 15–17% for non-air-conditioned interiors and 16–20% for exterior furniture.'],
    ['Which wood finish tolerates moisture movement best?', 'Oil and wax finishes, because they penetrate the wood rather than forming a film and so move with the substrate. Paint is the least tolerant, since movement of even 1–2% cracks the film, and lacquer sits in between, with water-based lacquers more sensitive to high-moisture timber.'],
    ['How long should timber acclimatise before finishing?', 'At least 5–7 days stacked in the production environment. The surface equilibrates quickly but the core lags, so finishing too early risks movement after the finish is applied. Check incoming stock with a moisture meter and reject or delay any batch more than 2% above the target.'],
  ],
  'solid-timber-vs-panel-board-furniture': [
    ['When should furniture use solid timber instead of panel board?', 'Use solid timber where grain is part of the design, where structural strength is needed (chair legs, table aprons, load-bearing frames), for pieces that will be repaired and refinished over decades, and for narrow or short components. Use panel board for flat, stable surfaces, wide components, painted or veneered surfaces and hidden internal parts. High-quality furniture often uses both.'],
    ['How much does solid timber move with humidity?', 'A solid timber panel 600mm wide moves roughly 6–12mm across its width between the driest and most humid conditions it meets in service. Designs that fix such a panel rigidly at both ends will crack the panel or fail the frame joint within a few years.'],
    ['How do you combine solid timber with panel board without cracking?', 'Let the solid timber component float within the frame using slotted screw holes, figure-8 fasteners or buttons, so it can move sideways while staying secured. This must be designed in from the start, not retrofitted after a failure.'],
  ],
  'rubberwood-vs-mahogany-furniture-comparison': [
    ['Is rubberwood or mahogany better for furniture?', 'Neither wins outright. Rubberwood is the volume timber: typically 40–60% cheaper per cubic metre with slightly better machinability and finish consistency. Mahogany is the premium choice with richer colour and ribbon figure on quartersawn faces. The decision is mostly about price and market positioning.'],
    ['Does mahogany furniture timber need treatment in Sri Lanka?', 'Mahogany needs kiln drying as standard and VPI treatment is strongly recommended wherever termites are active, which is most of the country. For export furniture where buyers require treatment documentation, treat mahogany to the same standard as rubberwood.'],
    ['What is the density of rubberwood and mahogany?', 'Rubberwood is about 540–630 kg/m³. Mahogany (Khaya or Swietenia) is about 450–650 kg/m³ depending on species and age.'],
  ],
  'furniture-factory-timber-drying-specification': [
    ['What should a furniture timber input specification cover?', 'Six areas: species (including excluded substitutes), dimensions and tolerances, moisture content with measurement method and documentation, treatment (for rubberwood, kiln drying and VPI with batch records), grade, and the maximum degrade allowance before a delivery is rejected.'],
    ['What moisture content should a furniture factory specify?', 'Base it on the equilibrium moisture content of your factory and of the finished piece\'s service environment. For a non-air-conditioned factory producing for air-conditioned homes specify 12–15%; for an air-conditioned factory specify 10–12%. Measure with a calibrated pin meter with species correction, at the face and both ends of each sampled board, on at least 10% of boards per delivery.'],
    ['When should a timber delivery be rejected?', 'When it arrives without treatment records, or when measured moisture content is consistently more than 3% above specification. Reject it or hold it pending supplier confirmation, and log every delivery with date, supplier, species, batch, readings and decision.'],
  ],
  'common-structural-timber-failures-sri-lanka': [
    ['What is the most common structural timber failure in Sri Lanka?', 'Termite damage to roof structures. Subterranean termites enter through the foundation, climb mud tubes along masonry walls and attack rafters, purlins and wall plates from the inside out, with damage invisible until it is severe. Specifying VPI borate treatment for all roof structural members before installation prevents it.'],
    ['How do you detect rot in timber wall plates?', 'Decay in wall plates is slow and silent: a plate can keep its shape while being structurally hollow after three to five years. A screwdriver probe test is the only way to detect it without opening the ceiling. Prevention is VPI-treated wall plates with a damp-proof layer between the timber and the masonry.'],
    ['Why do doors and joinery warp after installation?', 'The timber was at a higher moisture content than its final environment when installed and then dried in place. Process interior joinery at 12–15% moisture content; timber made from air-dried stock at 20–25% will move significantly after installation.'],
  ],
  'timber-lintels-wall-plates-embedded-treatment': [
    ['Why is timber in contact with masonry the highest-risk timber in a building?', 'Masonry is permanently porous and holds moisture, which keeps timber above the 20% moisture content at which fungal decay and termite activity thrive. The timber is also concealed behind plaster and ceilings and is hard to inspect, so a wall plate can be hollow after three years before anyone notices.'],
    ['How should wall plates be treated?', 'Kiln-dry to 15–18% moisture content, VPI-treat with borate preservative to confirmed retention at an IPPC-registered facility, place a damp-proof course membrane between the masonry and the timber, obtain treatment records before the ceiling conceals the plate, and inspect at 5-year intervals if accessible.'],
    ['What should a specification say about masonry-contact timber?', 'That all timber in contact with or within 300mm of masonry is kiln-dried to 15–18% moisture content and VPI-treated with borate preservative to a minimum retention of 3.5 kg/m³, with a continuous damp-proof course at all bearing faces and treatment records submitted before masonry or plaster conceals the members.'],
  ],
  'roof-timber-specification-guide-sri-lanka': [
    ['What moisture content should roof timber be at installation?', 'All structural roof timber should be installed at 15–18% moisture content. Timber installed above 20% dries in place, shrinking and loosening fixings, so require moisture data in the delivery documentation and verify it on receipt.'],
    ['What treatment retention should roof timber have?', 'VPI treatment with borate preservative to a minimum retention of 3.0 kg/m³ for above-ground interior structural use, from an IPPC-registered facility, with treatment records submitted before ceiling installation. Site-cut ends should be flood-coated immediately with concentrated borate solution.'],
    ['Which timber species suit structural roof members in Sri Lanka?', 'Pine, mahogany and, for premium applications, teak. Rubberwood is not appropriate for large-span structural roof members because of its moderate strength and its susceptibility to pests without treatment.'],
    ['What fixings should be used with treated roof timber?', 'Hot-dip galvanised as a minimum for interior structural use, and stainless steel for exposed or coastal applications, including nail plates, joist hangers and truss connectors.'],
  ],
  'timber-floor-joists-specification-failures': [
    ['Why do timber floor joists fail more often than roof timber?', 'Floor joists often sit in masonry pockets that trap moisture, run close to bathrooms and kitchens where moisture is highest, and are hidden above and below. Failure is typically silent until the floor visibly deflects, by which point the infestation has spread well beyond the visible damage.'],
    ['How should floor joists be treated and detailed?', 'Kiln-dry all joists to 15–18% moisture content and VPI-treat them with borate preservative before installation. Prefer steel joist hangers over embedded masonry pockets; where pockets are used, treat the ends and isolate the bearing face with a damp-proof membrane. Obtain treatment records before the floor boarding conceals the joists.'],
    ['How often should elevated timber floors be inspected?', 'Every five years, through inspection hatches or by lifting a section of floorboard, probing joist bearing ends and mid-spans for softness and checking the sub-floor for mud tubes and moisture. A joist that gives way to the probe is a structural emergency: prop the floor and replace the affected members.'],
  ],
  'timber-in-contact-with-masonry-risk': [
    ['How wet is timber that touches masonry?', 'Even in buildings with no visible dampness, timber in direct masonry contact may sit at 22–28% moisture content, which is above the threshold for fungal decay and within the range subterranean termites need to establish a colony.'],
    ['Why do masonry-contact timbers need both VPI treatment and a damp-proof membrane?', 'VPI treatment gives chemical resistance to termites and decay fungi through the whole cross-section but does not stop moisture absorption, while a damp-proof course reduces moisture transfer from the masonry. Used together they extend service life by decades compared with either alone, and neither alone is sufficient in high-risk or coastal environments.'],
    ['How quickly does untreated timber fail in masonry contact?', 'Fungal decay can establish within 2–3 years in embedded or enclosed positions under persistently wet conditions, significant structural decay is common by years 5–8 in the most vulnerable positions, and by years 10–15 remediation can involve major structural work.'],
  ],
  'building-with-timber-sri-lanka-regulations': [
    ['What regulations govern structural timber in Sri Lanka?', 'A combination of national standards, local authority by-laws and professional guidelines. The primary structural document is the Sri Lanka National Annex to the Eurocode system, which the country is progressively adopting, alongside ICTAD specifications and guidelines.'],
    ['Does timber need preservative treatment under Sri Lankan specifications?', 'ICTAD specification CS-02 and the Public Works Department general conditions require treatment in specific applications: ground-contact timber needs a ground-contact-rated preservative such as CCA (borate leaches in ground contact), and structural timber in buildings must be treated against termites and decay for its exposure class. For most above-ground structural uses, VPI treatment with borate satisfies the requirement.'],
    ['What must building plans state about structural timber?', 'The species, sizes and treatment specification. Plans that say only timber rafters without dimensions, species or treatment are increasingly challenged at approval, and treatment records should be kept as part of the building compliance file.'],
  ],
  'how-to-specify-treated-timber-building-projects': [
    ['What should a timber treatment specification include?', 'Four elements: the scope (every member type that needs treatment), the treatment method (VPI with borate, not surface application), the minimum retention in kg/m³, and the documentation required, including what is submitted, when and to whom.'],
    ['What retention should be specified for structural timber?', 'The guide\'s sample clauses specify a minimum borate retention of 3.0 kg/m³ for structural roof timber and 2.5 kg/m³ for door and window frames, sub-frames and sill members, all by an IPPC-registered treatment facility.'],
    ['What is a hold point for timber treatment records?', 'A stage in the programme at which records must be submitted before later work can proceed. Two are essential: records for structural roof timber before ceiling installation, and records for framing and joinery before plastering. At each, verify the facility name and IPPC registration number, batch date, species and dimensions, VPI cycle parameters and achieved retention.'],
  ],
  'timber-treatment-new-build-vs-renovation': [
    ['Is timber treatment necessary in new construction?', 'Yes. In a new build treatment is purely preventive, and the tools for it (species choice, moisture control, factory VPI, damp-proof isolation at masonry contacts and documentation before concealment) are cheap and easy to use, but none are available once the building is finished. Not specifying treatment means accepting future remediation cost as a certainty.'],
    ['What should be done about an active termite colony found during renovation?', 'Treat the colony before installing new structural timber. VPI-treated replacements reduce re-infestation risk but do not eliminate the colony, which survives in the soil. Options include soil barrier treatment, baiting systems and physical barriers, chosen by construction type, soil access and severity.'],
    ['What is in-situ borate treatment?', 'Drilling a grid of holes in a sound member and injecting concentrated borate solution, which diffuses through the moisture in the wood. It protects timber at risk without full replacement, but its penetration and retention do not match factory VPI, so it is a remedial measure rather than a substitute.'],
  ],
  'how-to-inspect-timber-batch-before-delivery': [
    ['How do you inspect a timber delivery?', 'In five steps: check the treatment documentation first, measure moisture content with a calibrated meter on boards from different stack positions (at least three readings per board), inspect for visible defects on 5–10% of boards, verify dimensions and piece count, then accept or reject. An experienced buyer can do this in 20–30 minutes.'],
    ['When should a timber delivery be rejected?', 'When documentation is absent, when moisture content is consistently more than 3% above specification, when significant structural defects such as ring shake, honeycombing or severe case hardening appear in more than 10–15% of sampled pieces, or when dimensions are systematically short. Record any rejection in writing before the lorry leaves.'],
    ['What documents should come with treated structural timber?', 'A treatment batch record showing species, cross-section, pre-treatment moisture content, VPI cycle parameters, retention, treatment date, and the treating facility\'s name and IPPC registration number. Export pallets also need ISPM 15 compliance documentation.'],
  ],
  'reaction-wood-timber-defect': [
    ['What is reaction wood?', 'Abnormal wood a tree produces on one side when it grows at an angle, as a response to gravity and wind stress. Compression wood forms on the underside of leaning softwood trunks and is dense and brittle; tension wood forms on the upper side of leaning hardwood trunks and has a gelatinous layer that tears when machined.'],
    ['Why does compression wood make boards bow?', 'It shrinks along the grain up to ten times as much as normal wood during drying, so a board containing both bows severely as the compression side contracts. It is also brittle in tension and fails at lower stress with less warning.'],
    ['How can you identify tension wood in hardwood?', 'The clearest sign is a woolly or hairy surface after planing, because the gelatinous cell wall layer tears rather than cutting cleanly. Blotchy stain absorption and finish adhesion problems also point to it.'],
  ],
  'timber-knots-grading-structural-impact': [
    ['What is knot area ratio in timber grading?', 'Knot diameter divided by board width. A 40mm knot in a 150mm board gives 0.27, while the same knot in a 75mm board gives 0.53. European C24 grade limits the ratio to 1/4 in the critical zone, which is why knot limits are expressed relative to board width.'],
    ['Which knots are most serious for structural timber?', 'Dead knots, which can fall out and leave a knot hole, are more serious than tight knots. Position matters too: a knot on the tension face of a bending member, or in the middle third of the span where bending moment is highest, is worse than the same knot on the compression face or near a support.'],
    ['Are knots a defect in timber?', 'Knots are a natural feature of how trees grow, not a manufacturing defect, but they cause localised grain deviation and stress concentration that affect mechanical performance. For furniture, lower appearance grades are often adequate because the yield of clear cuttings can be nearly as high at a much lower cost.'],
  ],
  'blue-stain-timber-does-it-matter': [
    ['What causes blue stain in timber?', 'Staining fungi growing in freshly sawn, wet, warm timber, conditions almost always present in Sri Lanka if green timber is left unprocessed. Pine and rubberwood are especially susceptible, and stain develops within days to weeks of sawing. Kiln drying kills the fungi and stops further stain but does not remove stain already formed.'],
    ['Can blue stain be removed from timber?', 'No. The discolouration is permanent and cannot be removed by drying, planing or any surface treatment, because the pigmented fungal threads are inside the cell cavities.'],
    ['When should blue-stained timber be rejected?', 'For appearance-grade work where the stain will show, where staining comes with surface softening that suggests incipient decay, and for export timber where the destination market prohibits sapwood staining. It can be accepted where it will be concealed or where the structural grade permits it.'],
  ],
  'fungal-decay-timber-identification': [
    ['What conditions do wood-decay fungi need?', 'Four at once: moisture above about 20% moisture content, oxygen, a temperature between 5°C and 40°C and an organic food source. Removing any one stops activity, and moisture is the most practical lever, since timber at 18–20% or below will not decay.'],
    ['How do you identify rot in structural timber?', 'Probe suspect areas with a screwdriver, awl or knife: sound timber resists, decayed timber does not. Brown rot leaves a brown residue that cracks into cuboid blocks and eventually crumbles under finger pressure, while white rot leaves a bleached, spongy, stringy surface. Check timber embedded in masonry, near gutters and roof penetrations, and anywhere discoloured.'],
    ['How do you stop active decay and prevent it returning?', 'Fix the moisture source first, since decay cannot continue below 20% moisture content. Replace structurally compromised members rather than reinforcing them, use in-situ borate treatment on adjacent sound timber, and specify VPI-treated replacement timber.'],
  ],
  'case-hardening-kiln-drying-defect': [
    ['What is case hardening in kiln-dried timber?', 'A condition of locked-in stress where the outer layers of a board are in compression and the core is in tension, because the surface dried and set while the core was still wet. It is invisible from the outside, so a case-hardened board can look identical to a properly dried one.'],
    ['How do you test for case hardening?', 'Rip the board lengthwise: if the two halves spring toward each other and pinch the blade, the core is in tension. A prong test confirms conditioning has worked, since a prong cut from the end should stay straight rather than bending inward or outward.'],
    ['How is case hardening prevented or corrected?', 'Prevention is through schedule design, starting with high humidity to slow surface drying and reducing humidity as the core dries. Existing case hardening needs a conditioning stage, steaming at high humidity at the end of the cycle; timber that arrives case-hardened cannot be fixed without a conditioning chamber.'],
  ],
  'shakes-ring-shake-timber-defect': [
    ['What is the difference between heart shake, ring shake and wind shake?', 'Heart shakes radiate from the pith outward; ring shakes follow growth ring boundaries and may be entirely internal; wind shakes run across the grain from storm bending stress and look fibrous and torn. All reduce shear capacity.'],
    ['Why is ring shake the most dangerous timber defect?', 'It can be completely invisible on all four faces and both ends, and only shows when the board is cross-cut or fails. In rafters and floor joists, where horizontal shear is highest near the supports, a shake at mid-depth can cause sudden failure under peak load with almost no warning.'],
    ['How do you check for shakes at delivery?', 'Inspect the end grain of every piece in a structural delivery, where heart shakes show as radial cracks and ring shakes as separations along ring boundaries. Reject any timber with a ring shake visible on the end for structural use, regardless of its face grade.'],
  ],
  'slope-of-grain-timber-defect': [
    ['What slope of grain is acceptable for structural timber?', 'Most higher structural grades limit slope of grain to 1:10 or 1:12, and lower grades allow 1:6. Below 1:4 the timber should be rejected for structural use.'],
    ['How do you measure slope of grain?', 'Look at the surface grain lines: lines parallel to the edge mean straight grain, diagonal lines mean sloped grain. For a field test use the scribe method, scratching along the grain and measuring the offset against the distance along the board.'],
    ['What causes sloped grain?', 'Either a sawing error, such as a straight-grained log fed at an angle, or inherent spiral or interlocked grain in the log that no sawmill technique can correct. A board can look good on appearance yet have a grain slope that limits its structural value.'],
  ],
  'how-to-grade-timber-sri-lanka': [
    ['What is the difference between structural and appearance grading?', 'Structural grading assesses features that affect load-bearing performance (knots, slope of grain, checks, wane, warp) and assigns design strength values; appearance grading assesses visual quality without regard to strength. For construction specify by structural grade; for exposed finishes specify by appearance grade.'],
    ['What do timber grade marks like C24 and MGP10 mean?', 'They are structural grade designations: C16 and C24 in European standards, MGP10 and MGP12 in Australian standards. A mark also shows the species or group, the moisture content at grading and the certification body, and gives a predictable minimum bending strength and stiffness for design.'],
    ['How is structural timber graded?', 'By visual inspection, where a trained inspector assesses limiting defects, especially in the critical middle third of the length, or by machine, which measures stiffness directly with a roller. Machine grading is faster and more consistent but less effective at spotting localised defects such as large knots or shakes.'],
  ],
  'timber-species-for-construction-sri-lanka': [
    ['What is the best timber for roof structures in Sri Lanka?', 'Imported pine is the most widely used, and kiln-dried, VPI-treated pine is an excellent choice where budget is the priority. Mahogany is a step up for large-span beams and applications that are hard to inspect, and teak suits premium exposed elements.'],
    ['Does teak need preservative treatment?', 'Teak heartwood has very high natural durability, but treatability is low because its oils repel water-borne preservatives, and teak sapwood still benefits from treatment. Natural durability reduces but does not eliminate the benefit of VPI treatment.'],
    ['Does all structural timber in Sri Lanka need treatment?', 'Regardless of species, structural timber should be kiln-dried to 15–18% moisture content and VPI-treated with borate before installation in roof structures, floor framing or joinery. For vulnerable species such as pine and rubberwood treatment is not optional if the structure is expected to last.'],
  ],
  'timber-species-for-furniture-sri-lanka': [
    ['What is the best timber for furniture in Sri Lanka?', 'Rubberwood is the dominant volume furniture timber, mahogany is the quality step up, teak is the premium choice, and jak is a local alternative. The right one depends on cost, appearance and market.'],
    ['Does rubberwood furniture need VPI treatment?', 'Yes. All rubberwood for furniture should be kiln-dried to 12–15% moisture content and VPI-treated with borate. Kiln drying kills beetles already present and VPI prevents re-infestation, and beetle emergence in delivered furniture is the most common quality complaint in the industry.'],
    ['Why isn\'t jak wood more widely used for furniture?', 'Supply consistency. Unlike plantation-grown rubberwood, jak is not grown in managed plantations and comes from scattered sources, so dimensions and grades are less predictable. It suits custom makers who can select and process their own timber.'],
  ],
  'rubberwood-complete-guide': [
    ['What is rubberwood?', 'Timber harvested from rubber trees (Hevea brasiliensis) at the end of their 25–30 year latex-producing life. It was once burned as waste but is now one of Asia\'s most important furniture timbers. Sri Lanka\'s rubber plantations are concentrated in Sabaragamuwa, Western and Southern Provinces, making rubberwood a genuinely local, renewable resource.'],
    ['Why is rubberwood so prone to beetle attack?', 'Its sapwood stores high concentrations of starch, which is an ideal food source for Lyctus powder post beetles. Untreated rubberwood kept in a sawmill or workshop for more than a few weeks is at risk, and finished furniture can show exit holes within months. Kiln drying above 55°C kills all beetle life stages and VPI treatment protects against re-infestation.'],
    ['Where should rubberwood not be used?', 'In ground contact, in exterior furniture exposed to rain, and anywhere borate treatment would be leached by water. It is also a second choice behind pine or mahogany for large structural members because of its moderate strength and the treatability limits of thick heartwood sections.'],
  ],
  'teak-timber-properties-uses-sri-lanka': [
    ['Why is teak so durable?', 'Teak heartwood contains tectoquinone and other natural extractives that act as preservatives, making it resistant to termites, wood-boring insects and fungal decay. They also repel water, so teak swells and shrinks very little with humidity changes.'],
    ['How much more does teak cost than other timbers?', 'Typically 4–8 times the cost per cubic metre of pine or rubberwood, depending on grade and source. It is justified for outdoor furniture, premium joinery, exposed structural features and high-value door and window frames; a teak garden set maintained with annual teak oil can last 30–50 years in Sri Lanka.'],
    ['Where does teak used in Sri Lanka come from?', 'Domestic supply is limited and inconsistent. Most teak is imported from Myanmar, India and plantations in Central America and West Africa. Old-growth teak has higher density, more extractives and better durability than fast-grown plantation teak.'],
  ],
  'pine-timber-sri-lanka-guide': [
    ['Which pine species are sold in Sri Lanka?', 'Mostly radiata pine from New Zealand and Chile, South American species such as Pinus taeda and Pinus elliottii, and European redwood (Pinus sylvestris) from Scandinavia and the Baltic. Radiata is the most price-competitive and widely available; European redwood is slower-grown, denser and stronger.'],
    ['Why does structural pine need treatment in Sri Lanka?', 'Pine has low natural durability and both heartwood and sapwood are open to termite attack, with year-round termite activity in the tropics. It responds very well to VPI, because its open tracheid structure lets borate penetrate deeply and uniformly.'],
    ['What should I check when buying construction pine?', 'Moisture content of 15–18% with measurement records, VPI treatment with batch records from an IPPC-registered facility, the structural grade, and that actual dimensions match nominal. Reject timber that is visibly bowed, twisted or deeply checked.'],
    ['Do pine pallets need ISPM 15 treatment?', 'Export pallets do: they need ISPM 15 heat treatment by an IPPC-registered facility and the HT mark on every pallet. Domestic pallets do not, but benefit from kiln drying because green pallet timber is significantly heavier.'],
  ],
  'mahogany-timber-sri-lanka-guide': [
    ['Which species are sold as mahogany in Sri Lanka?', 'Genuine mahogany (Swietenia macrophylla), African mahogany (Khaya species) and Philippine mahogany (Shorea and Parashorea species), which is unrelated and generally inferior. Most mahogany sold in Sri Lanka is Khaya from West Africa, which is a genuine high-quality hardwood.'],
    ['What moisture content should kiln-dried mahogany be?', 'Furniture mahogany should be dried to 12–15% moisture content, and structural and joinery mahogany to 15–18%. Mahogany needs a careful schedule and end coating before drying because its interlocked grain can distort and its ends are prone to splitting.'],
    ['Does mahogany need VPI treatment in Sri Lanka?', 'Its moderate natural durability is adequate for interior above-ground use in low-risk conditions, but because termite activity is widespread VPI treatment adds a meaningful margin, especially for door and window frames in contact with masonry and for coastal or humid sites. Mahogany sapwood is much less durable and should always be treated.'],
  ],
  'jak-wood-sri-lanka-guide': [
    ['What is jak wood used for?', 'Traditionally for furniture, construction and musical instruments, including the jak wood drum (yak bera). Today it suits bespoke furniture, decorative screens and feature panels, and flooring for heritage restoration. It is less suited to volume production because supply is inconsistent.'],
    ['Is jak wood durable?', 'Jak heartwood has moderate to good natural durability, better than rubberwood and comparable to mahogany for above-ground interior use. The sapwood is far less durable and should be excluded from structural use or treated with VPI, which adds an inexpensive margin of protection against termites.'],
    ['Why do jak furniture pieces fail?', 'Most failures come from buying jak from a small sawyer or straight off the tree and using it green. Verify moisture content at purchase, confirm whether any drying was done, and arrange kiln drying and treatment before use.'],
  ],
  'coconut-timber-sri-lanka-guide': [
    ['What is coconut timber?', 'Timber from the stem of coconut palms felled at the end of their productive life, typically 60–80 years. A palm has no rings, heartwood or sapwood, just vascular bundles in a softer matrix. The outer 2–3 inches (high-density grade) is 700–900 kg/m³ and very hard; the inner zone is only 200–400 kg/m³.'],
    ['Where is coconut timber best used?', 'Flooring, where the hardness and abrasion resistance of the outer material is an asset and its unusual appearance is a feature. Structural use is possible with selected high-density material but limited by stem diameters of 200–400mm, and it does not replace sawn timber in conventional framing or roofs.'],
    ['What are the limitations of coconut timber?', 'It blunts conventional tools and needs specialised tooling, fixings hold in the hard outer zone but not in the soft parenchyma, and supply is informal and not graded, so buyers must inspect and explicitly select outer-zone material.'],
  ],
  'imported-vs-local-timber-sri-lanka': [
    ['Should I use imported or local timber in Sri Lanka?', 'It depends on the job. Imported kiln-dried, VPI-treated pine suits structural roof and floor framing; local rubberwood suits volume furniture; imported mahogany or teak suits premium joinery and frames; coconut timber suits feature flooring; and jak suits heritage or bespoke furniture.'],
    ['Why choose local rubberwood?', 'It has a complete local supply chain with no import dependence, shorter transport, and no exchange-rate or import duty exposure, so it offers price stability. It is also harvested at the end of its latex-producing life, without clearing land for timber.'],
    ['What timber does Sri Lanka import?', 'Primarily pine from New Zealand, Australia and South America, and various hardwoods from Africa, Southeast Asia and South America. Domestic production is mainly rubberwood, coconut palm timber, jak and small volumes of other species.'],
  ],
  'vpi-vs-surface-treatment-timber': [
    ['How deep does surface treatment penetrate timber?', 'Coating depth rarely exceeds 1–2mm, so the preservative sits on the wood rather than in it. It is also absent or abraded at the points where attack usually happens: joints, cut ends, checks and masonry contact.'],
    ['How do termites and borers get past surface treatments?', 'Subterranean termites enter through end grain and the uncoated underside of timber resting on masonry, drywood termites fly in through cracks and joints, and beetles lay eggs in exposed end grain and cracks, so larvae feed in the interior that no surface treatment reached.'],
    ['How does borate preservative kill pests?', 'It acts when ingested, not on contact. Termites and borers that eat treated wood cannot metabolise nutrients and die, so a pest that gets in through a drilled fixing hole still meets active preservative throughout the member.'],
    ['When is surface treatment acceptable?', 'For exterior timber regularly maintained with preservative oil or paint, in places with no subterranean termite pressure, for decorative interior timber in dry conditioned spaces, and as a remedial measure on existing structures where VPI is not possible.'],
  ],
  'vpi-treatment-rubberwood-furniture': [
    ['Why isn\'t kiln drying alone enough to protect rubberwood furniture?', 'Kiln drying, with core temperatures typically 60–75°C, kills every beetle life stage present at the time, but gives no ongoing protection. Adult Lyctus beetles can re-infest the dried timber in a sawmill, factory or showroom, whereas VPI borate stays active for the life of the piece.'],
    ['In what order should rubberwood be kiln dried and VPI treated?', 'Kiln drying first, then VPI. Drying to 12–15% moisture content improves borate penetration and retention and kills beetles before treatment, whereas VPI on green or partly dried rubberwood gives lower and less uniform retention.'],
    ['What are the first signs of beetle infestation in furniture?', 'Fine powdery frass (boring dust) falling from small circular holes in the surface, often weeks or months after the piece reaches the customer.'],
  ],
  'vpi-treatment-coastal-high-humidity': [
    ['Why is the coast so hard on timber in Sri Lanka?', 'Humidity is often above 80% within a few kilometres of the sea, keeping untreated timber above 18–20% moisture content, well over the decay threshold. Salt deposits attract and hold extra moisture and coastal winds drive water into joints and end grain. Coastal soils also favour termite activity.'],
    ['What is the minimum specification for coastal structural timber?', 'Within about 5km of the coast or in consistently humid areas: kiln-dry to 15–18% moisture content, then VPI-treat with borate to verified deep penetration and retention, with records from an IPPC-registered facility. Exposed external timber also needs a high-build primer and top coat straight after treatment, and timber touching masonry should be isolated with a damp-proof course.'],
    ['Does borate treatment protect against marine borers?', 'No. Borate leaches readily in water contact, so for piers, jetties and other timber in direct water contact alternatives such as CCA, creosote or physical encapsulation are required.'],
  ],
  'vpi-treatment-door-window-frames': [
    ['Why are door and window frames vulnerable to termites?', 'They sit in masonry openings, which gives termites a concealed pathway; the end grain is embedded in the masonry; and the back face and ends are usually left bare before installation, so hidden surfaces get no protection. Frames are often the original entry point when termite damage is found in a building.'],
    ['How should door and window frames be treated?', 'VPI-treat all frames, sub-frames, sill members and architraves with borate before installation, treating dimensioned sections before final cutting and assembly. Flood-coat any site cuts with concentrated borate solution, isolate the back face from masonry with a damp-proof membrane, and require treatment records from an IPPC-registered facility.'],
    ['How can you tell a frame has termite damage?', 'Termites hollow the frame while leaving the painted surface intact, so signs are a frame that feels soft or hollow when knocked, bubbling or peeling paint, or in bad cases collapse under normal use. By then the infestation has usually spread well beyond the frame.'],
  ],
  'boron-borax-vs-other-timber-preservatives': [
    ['What is borate (Boron Borax) wood preservative and how does it work?', 'Disodium octaborate tetrahydrate, applied by VPI for interior and above-ground use. It disrupts the digestive enzymes of wood-destroying insects, making wood indigestible and lethal to termites, powder post beetles and borers, and it inhibits fungal growth.'],
    ['Is borate wood preservative safe?', 'At the concentrations used in timber treatment it is non-toxic to mammals, in the same general toxicity category as common salt. It leaves no harmful residue in sawdust, does not off-gas in enclosed spaces and needs no special handling or respiratory protection during installation.'],
    ['What are the limits of borate treatment?', 'It is water-soluble and leaches in repeated water contact, so it is unsuitable for ground contact, rain-washed exteriors and marine use. CCA is more appropriate for ground contact such as fence posts and pergola uprights set in soil.'],
    ['Why is CCA restricted?', 'CCA contains copper, chromium and arsenic. It is restricted or banned for residential use in many markets because of skin contact and disposal concerns; CCA-treated timber cannot be burned as the ash concentrates arsenic. For homes, furniture and play equipment borate is the correct choice.'],
  ],
  'vpi-treatment-different-timber-species': [
    ['Which timber species are easiest to treat with VPI?', 'Rubberwood is one of the most treatable, with wide open vessels and high sapwood content. Pine is generally highly treatable, mahogany is moderately treatable with variable heartwood penetration, and teak heartwood is the hardest because its natural oils repel water-borne preservatives, giving only a few millimetres of penetration.'],
    ['Why does sapwood take preservative better than heartwood?', 'Sapwood pits are still open and absorb liquids readily, while heartwood pit membranes are aspirated or encrusted with extractives that resist penetration. Treatability therefore depends on the sapwood-to-heartwood proportion of the cross-section.'],
    ['Why must timber be kiln dried before VPI treatment?', 'Wet wood has no empty cell space for preservative. Timber dried to 12–18% moisture content has most of its free water removed, so VPI achieves higher retention and more uniform penetration, significantly so for less treatable species.'],
    ['What should a VPI treatment record show?', 'Species, cross-section, moisture content before treatment, vacuum level and duration, preservative concentration and volume absorbed, pressure level and duration, and the final retention in kg of preservative per cubic metre, which is the key figure.'],
  ],
  'how-to-specify-vpi-treatment-construction': [
    ['What should a VPI treatment specification say?', 'It should define every element to be treated, require VPI with borate rather than surface application, state a minimum retention (typically 2.5–4.0 kg/m³ for above-ground interior use), require kiln drying to 15–18% moisture content before VPI, require an IPPC-registered facility, and require batch records before plastering or concealment.'],
    ['What are the most common specification mistakes?', 'Writing treated timber without defining the treatment, so a surface preservative can be substituted for VPI; requiring treatment without requiring documentation; and not requiring kiln drying before VPI, which lets a contractor treat green timber at a lower effective retention.'],
    ['Which timber elements are most often left out of treatment specifications?', 'Door and window sub-frames, timber embedded in or within 300mm of masonry, timber at or near floor level in the roof space, and structural timber in contact with concrete.'],
  ],
  'what-does-10-year-timber-pest-warranty-cover': [
    ['What does the St. Xavier Timber 10-year pest warranty cover?', 'Failure of correctly treated and correctly installed VPI timber due to attack by termites and wood-boring insects within 10 years of treatment. It is backed by the batch treatment records, which document species, dimensions, pre-treatment moisture content, VPI cycle, concentration and achieved retention.'],
    ['What is not covered by the pest warranty?', 'Fungal decay from prolonged water contact, damage from ground contact or repeated rain wash, and mechanical damage, overload or fire. It applies only to dry, sheltered, above-ground installations, because borate is not designed for wet or ground conditions, and the original treatment records must be retained.'],
    ['How do I make a pest warranty claim?', 'Contact St. Xavier Timber with the original treatment record, the installation date and a description of the symptoms and location, such as exit holes, boring dust, mud tubes or soft or hollow sections. An inspection is arranged to confirm the nature and cause of the damage.'],
  ],
  'what-is-fibre-saturation-point': [
    ['What is the fibre saturation point of timber?', 'The moisture content at which all free water has left the cell cavities but the cell walls are still fully saturated with bound water. For most species it is between 25% and 30%, with 28% a common working figure.'],
    ['Why does timber only shrink below the fibre saturation point?', 'Above it the cell walls are fully hydrated, so removing free water changes no dimensions. Below it each 1% drop in moisture content causes roughly 0.25–0.35% tangential and 0.15–0.20% radial shrinkage; a 100mm flat-sawn rubberwood board dried from 28% to 12% shrinks about 3–4mm in width.'],
    ['How does drying below the fibre saturation point affect timber strength?', 'Strength rises as bound water leaves. Bending strength roughly doubles between 28% and 12% moisture content and stiffness increases by about 50%, which is why timber specified for dry conditions loses much of that advantage if it is re-wetted.'],
  ],
  '7-kiln-drying-myths': [
    ['Does kiln-dried timber stay dry?', 'No. Wood stays hygroscopic for life, so timber dried to 12% and then stored outdoors in Sri Lanka can return to 18–22% within weeks. Check moisture content at the point of use, ask for the drying date and inspect storage conditions before accepting a delivery.'],
    ['Does thicker timber take proportionally longer to dry?', 'No, drying time scales roughly with the square of thickness, so a 50mm board takes about four times as long as a 25mm board of the same species. Mixing thick and thin pieces in one load over-dries the thin ones while the thick ones are still wet.'],
    ['Does kiln drying weaken timber?', 'No, properly kiln-dried timber is stronger than green timber: bending strength roughly doubles between 28% and 12% moisture content and stiffness rises by about 50%. Only aggressive or incorrect schedules that cause checking and internal cracking reduce strength.'],
    ['Can you tell good timber by looking at it?', 'No. Timber at 25% moisture content can look identical to timber at 12%, and internal drying stresses are invisible until the timber is machined. Only a calibrated meter or oven-dry test shows moisture content, and only drying records show whether a batch was dried correctly.'],
  ],
  'common-kiln-drying-defects': [
    ['What causes surface checking in kiln-dried timber?', 'The surface losing moisture faster than the core early in the cycle, putting the surface in tension until it splits. Mild checks under 2mm that close up have minimal impact, but severe open checks mean the initial drying conditions were too aggressive, with humidity too low or temperature too high.'],
    ['What is honeycombing and how do you detect it?', 'Internal cracking caused by reversed stress, where the set surface resists as the core dries and shrinks, so the core tears internally. It is invisible on the surface and strongly reduces shear strength, so diagnose it by cutting 2–3 cross-sections from a sample board in the batch.'],
    ['How is end splitting prevented?', 'Ends lose moisture about 10–15 times faster than faces, so a wax emulsion end coating is applied to cut ends before loading the kiln. Splits in a batch usually mean ends were uncoated or inconsistently coated.'],
    ['What is collapse in dried timber?', 'Permanent buckling of cell walls caused by too-high temperatures early in drying, above the fibre saturation point. It leaves a corrugated surface and smaller-than-expected dimensions. Mild collapse can be partly recovered by steam reconditioning; severe collapse cannot.'],
  ],
  'drying-hardwood-vs-softwood-timber': [
    ['Do hardwoods dry slower than softwoods?', 'Generally yes. Softwoods move moisture through open tracheid pits and dry faster, so pine at an initial 70°C can reach 15% moisture content in 3–5 days. Hardwood schedules start lower (50–60°C) at higher humidity, and a thick section of dense tropical hardwood may need 10–20 days to reach 12%.'],
    ['Why is rubberwood prone to cupping and checking if dried fast?', 'Its shrinkage is about 8.5% tangentially against 4% radially, a T/R ratio near 2.1, so flat-sawn boards cup and check under aggressive drying. It needs a high-humidity first stage with humidity reduced progressively, and should be kiln-dried within days of sawing rather than air-dried for weeks first.'],
    ['What happens if a softwood schedule is used on hardwood?', 'Surface checking within the first day or two, cupping in boards wider than about 100mm and, in extreme cases, collapse. These defects are not recoverable.'],
  ],
  'kiln-drying-schedules-explained': [
    ['What is a kiln drying schedule?', 'A set of instructions that changes dry-bulb temperature and wet-bulb depression through the drying cycle. A large wet-bulb depression means low humidity and fast drying; a small one means high humidity and slow drying.'],
    ['Why does a kiln schedule start at high humidity?', 'Low humidity from the start dries the surface faster than the core can supply moisture, so the surface shrinks while the core is still wet and checks. Starting at high humidity and raising the wet-bulb depression as the load approaches the fibre saturation point keeps the surface-to-core gradient small.'],
    ['What is conditioning at the end of kiln drying?', 'Steam injection that raises humidity so the slightly wetter core redistributes moisture outward and residual drying stresses relax. Conditioned timber has uniform moisture across its section and is far less likely to warp when machined; skipping it saves a few hours but is a false economy.'],
  ],
  'how-moisture-meters-work': [
    ['What is the difference between pin and pinless moisture meters?', 'Pin meters measure electrical resistance between pins that penetrate only about 5–8mm and are accurate from roughly 6–30% moisture content, with deep probes reaching 25–40mm for thick sections. Pinless capacitance meters read 20–40mm deep through a surface pad without marking the wood and suit scanning; confirm any outlier with a pin meter.'],
    ['What are the most common moisture meter mistakes?', 'Taking one reading and treating it as the board\'s moisture content, ignoring the species correction (an uncorrected reading on dense tropical hardwood can be 3–5 points off), measuring within 300mm of a cut end, and measuring cold timber, which reads wetter. Take at least three readings per board on both faces.'],
    ['What should I do if a moisture meter reading seems wrong?', 'Check the species correction and battery level, then check probe depth, since standard pins on thick timber may read a dry surface over a wet core. If readings stay above specification, request the supplier\'s drying cycle records.'],
  ],
  'why-timber-cracks-splits-during-drying': [
    ['Why does timber crack as it dries?', 'Differential moisture loss. The outer layers dry and shrink first while the wet core resists, putting the surface in tension until it splits as surface checks along faces and edges or as end splits at cut ends.'],
    ['Why do the ends of boards split?', 'Ends lose moisture roughly 10–15 times faster than faces, so the tip can be at 15% moisture content while material 50mm back is still at 40–50%. Applying a wax emulsion end coating before drying equalises the loss rate and prevents most end splitting.'],
    ['When are cracks in timber acceptable for structural use?', 'Shallow surface checks, under about one-sixth of the thickness and running with the grain, are accepted by most grading standards. Checks deeper than one-third of the section, end splits beyond 150–200mm and any crack running across the grain may affect the structural grade.'],
  ],
  'why-timber-warps-moisture-movement': [
    ['What are the four types of timber warp?', 'Bow (curvature along the length of the face), cup (curvature across the width), twist (spiral distortion along the length) and crook (curvature along the edge).'],
    ['Why does flat-sawn timber cup?', 'In flat-sawn boards the growth rings run roughly parallel to the face and the outer surface of each ring shrinks more than the inner, pulling the face inward. Cup is worst in wide boards and in species with a large difference between tangential and radial shrinkage.'],
    ['How do I stop kiln-dried timber warping after it leaves the kiln?', 'Stack it on flat, level bearers with stickers at no more than 600mm intervals in covered, ventilated storage out of sun and rain, acclimatise it to the workshop before machining and process it promptly. Process interior furniture timber at 12–15% moisture content.'],
  ],
  'what-is-timber-moisture-content': [
    ['What is timber moisture content?', 'The weight of water in wood as a percentage of the weight of the dry wood. A freshly felled tree can be at 50–120% depending on species, and below the fibre saturation point of about 28–30% the wood begins to shrink as cell walls lose water.'],
    ['What moisture content should timber be for different uses?', 'Furniture and interior joinery 12–15%, structural timber (roofs, floors, framing) 15–18%, export packaging typically 15–20%, outdoor furniture and decking 16–20%, and parquet and strip flooring 10–12%.'],
    ['What is the equilibrium moisture content in Sri Lanka?', 'In air-conditioned interiors at 60–70% relative humidity wood settles at about 12–14%, and outdoors in the shade at about 16–19%. Timber used well away from its equilibrium will move, causing warping, joint failure and cracked finishes.'],
    ['Why can\'t air-dried timber be used for finished products in Sri Lanka?', 'Air drying rarely brings timber below 18–20% in Sri Lankan climate, and does so slowly and unevenly, with the centre of a stack potentially still at 30%. It is acceptable for rough battens, formwork and scaffold planks, but furniture, joinery and flooring need kiln drying to a controlled target.'],
  ],
  'termite-protection-roof-timber-sri-lanka': [
    ['Why is roof timber at such high risk from termites in Sri Lanka?', 'Subterranean termites are active year-round, enter through the foundation and climb mud tubes along masonry to the roof space, then hollow out rafters and purlins from the inside while leaving a thin shell intact. Damage is rarely noticed until it is severe; a screwdriver pushed into an infested member passes straight through.'],
    ['How does VPI treatment protect roof timber?', 'Timber is loaded into a sealed vessel, a 45-minute vacuum removes air from the cells, then a 5% borate solution is applied at 10 bar (145 PSI) for 2–6 hours depending on species and thickness. The preservative reaches the core, and termites and borers that eat it cannot metabolise nutrients and die.'],
    ['Do surface treatments protect roof timber from termites?', 'No. Termites attack from within the wood and through cut ends and joints where coatings are absent, so a coat on the outside of a rafter is not a barrier. Re-treat any timber cut on site, since exposed end grain loses the protection.'],
  ],
  'what-is-ispm-15-heat-treatment': [
    ['What is ISPM 15?', 'A global standard from the International Plant Protection Convention governing wooden packaging in international trade. Pallets, crates and dunnage must be treated and marked to ISPM 15 before crossing most international borders, to prevent the spread of pests such as bark beetles and pine wood nematodes.'],
    ['What does ISPM 15 heat treatment require?', 'The entire cross-section of the wood must reach a core temperature of 56°C for at least 30 continuous minutes, verified by calibrated probes in the thickest piece of each batch, by an IPPC-registered facility. Heat treatment is preferred because methyl bromide is being phased out under the Montreal Protocol and is banned in many countries, including the EU.'],
    ['Are locally bought pallets automatically ISPM 15 compliant?', 'No. They are only compliant if made from timber treated by an IPPC-registered facility and correctly marked, so unmarked pallets from a hardware shop or small workshop are a compliance risk. Each export batch must be treated; reusing pallets is generally acceptable only if the mark is legible and the wood is unmodified.'],
    ['What does the IPPC mark show?', 'The country code (LK for Sri Lanka), the treatment facility\'s unique registration number and the treatment method code (HT for heat treatment). Customs authorities check for it, and a missing, incorrect or counterfeit mark is treated as untreated packaging.'],
  ],
  'kiln-drying-vs-air-drying-timber': [
    ['How long does air drying timber take in Sri Lanka?', 'Months to years depending on species and thickness. A 25mm rubberwood board might take 3–4 months to reach 18–20% moisture content outdoors, and will rarely get below 15% without kiln finishing.'],
    ['How long does kiln drying take?', 'Typically 3 to 12 days depending on species and target moisture content, reaching a consistent 12–15% for furniture and joinery or 15–18% for construction, and killing insects and their eggs as a by-product.'],
    ['When is air-dried timber acceptable?', 'For rough structural applications such as roof purlins on a simple warehouse, scaffold planks and temporary hoarding, provided the structure tolerates some movement. For furniture, door and window frames, finished flooring, tight-tolerance framing or export timber, kiln drying is a requirement.'],
  ],
  'what-is-vacuum-pressure-impregnation': [
    ['How does vacuum pressure impregnation work?', 'In a sealed vessel a vacuum first draws air and moisture out of the wood cells, then the chamber is flooded with borate preservative under pressure up to 10 bar (145 PSI), forcing it through the cross-section. After the cycle excess solution is removed and the boron fixes within the wood, so it does not wash off or evaporate under normal indoor or sheltered conditions.'],
    ['Is borate-treated timber safe?', 'Yes. Borate preservative is non-toxic to humans and animals at timber-treatment concentrations, heavy-metal free and classified as low-hazard, so it is safe for homes, schools and food-handling facilities. It is not suitable for ground contact or continuous water immersion.'],
    ['What does the 10-year warranty on VPI-treated timber cover?', 'Failure caused by termites and wood-boring insects in timber that was correctly treated to the specified retention and installed in dry, sheltered, above-ground conditions. It is backed by treatment records for every batch, including retention level, pressure cycle data, species and dimensions.'],
    ['Where is VPI treatment most useful?', 'Roof structures, floor joists and sub-floor framing, door and window frames, furniture (especially rubberwood, which is highly susceptible to borers), feature interior timber, and warehousing and storage structures.'],
  ],
  'why-furniture-manufacturers-need-kiln-dried-timber': [
    ['What moisture content should furniture timber be in Sri Lanka?', 'The industry standard for quality furniture is 12–15%. In air-conditioned interiors at 60–70% relative humidity timber stabilises at about 12–14%; above 15% it keeps drying and moving after manufacture, below 10% it may swell in humid conditions, and air-dried timber rarely reaches below 15–18% consistently.'],
    ['What is the real cause of most furniture rejects?', 'Timber movement, not joinery, finishing or hardware. Boards that warp before assembly, panels that cup after gluing and joints that open after delivery all trace back to timber that was not at a stable moisture content when processed.'],
    ['What should I ask a timber supplier before buying furniture timber?', 'Three questions: what is the current moisture content, how was it measured, and what drying method was used. A reputable kiln facility can provide batch-level moisture data; if a supplier cannot answer, the timber has not been dried to a controlled specification and the risk of movement falls on you.'],
  ],
  'how-to-choose-the-right-timber-treatment': [
    ['What is the difference between kiln drying and VPI treatment?', 'Kiln drying removes moisture, making timber dimensionally stable and ready for machining and finishing; VPI introduces a preservative that makes timber resistant to insects and fungal decay. Neither substitutes for the other.'],
    ['When is kiln drying alone enough?', 'For interior furniture in air-conditioned, low-pest-risk environments, decorative timber in dry enclosed settings, components fully encased in other materials, and wood that will receive regular surface maintenance.'],
    ['When is VPI treatment essential?', 'For roof structural timber, floor joists and sub-floor framing, timber in areas with known or suspected termite activity, rubberwood furniture and joinery, door and window frames in contact with masonry, and any timber in or near ground contact.'],
    ['What is a simple rule for choosing treatment in Sri Lanka?', 'Kiln dry everything, and VPI-treat anything structural, any rubberwood and any timber in exposed or high-humidity locations. Where both are needed, dry first, because VPI on poorly dried timber gives lower and less uniform retention.'],
  ],
};
